plugins/fontawesome-free/css/all.min.css
plugins/overlayScrollbars/css/OverlayScrollbars.min.css
dist/css/adminlte.min.css
plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css
plugins/icheck-bootstrap/icheck-bootstrap.min.css
plugins/jqvmap/jqvmap.min.css
plugins/daterangepicker/daterangepicker.css
plugins/summernote/summernote-bs4.min.css
plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css
plugins/select2/css/select2.min.css'
plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css
dist/img/AdminLTELogo.png
plugins/jquery/jquery.min.js
plugins/bootstrap/js/bootstrap.bundle.min.js
plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js
dist/js/adminlte.js
plugins/jquery-mousewheel/jquery.mousewheel.js
plugins/raphael/raphael.min.js
plugins/jquery-mapael/jquery.mapael.min.js
plugins/jquery-mapael/maps/usa_states.min.js
plugins/chart.js/Chart.min.js
dist/js/demo.js
dist/js/pages/dashboard2.js
plugins/select2/js/select2.full.min.js
